use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::sync::Mutex;

use super::types::AppInfo;
use super::{launchservices, scanner, uti};

#[derive(Serialize, Deserialize)]
pub struct Config {
    pub associations: BTreeMap<String, String>,
}

pub struct ImportResult {
    /// (extension key, new app name, previous app name if any)
    pub applied: Vec<(String, String, Option<String>)>,
    pub unchanged: Vec<(String, String)>,
    pub skipped: Vec<(String, String, String)>,
}

/// Export current file associations to a Config.
/// Values are bundle IDs (canonical, lossless for round-tripping).
pub fn export_associations(apps: &[AppInfo]) -> Result<(Config, BTreeMap<String, String>)> {
    let extensions = scanner::all_extensions(apps);

    let associations: Mutex<BTreeMap<String, String>> = Mutex::new(BTreeMap::new());
    let display_names: Mutex<BTreeMap<String, String>> = Mutex::new(BTreeMap::new());

    std::thread::scope(|s| {
        for chunk in extensions.chunks(20) {
            let associations = &associations;
            let display_names = &display_names;
            let chunk = chunk.to_vec();
            s.spawn(move || {
                for ext in chunk {
                    if let Some(bid) = launchservices::query_default_bundle_id(&ext).ok().flatten()
                    {
                        let key = format!(".{}", ext);
                        let name = scanner::resolve_name(apps, &bid);
                        if name != bid {
                            display_names.lock().unwrap().insert(key.clone(), name);
                        }
                        associations.lock().unwrap().insert(key, bid);
                    }
                }
            });
        }
    });

    Ok((
        Config {
            associations: associations.into_inner().unwrap(),
        },
        display_names.into_inner().unwrap(),
    ))
}

/// Import associations from a Config, applying each one.
/// Values can be bundle IDs or display names — both are accepted, and both
/// must resolve to an installed app. Associations already set correctly are
/// left untouched, so import is idempotent. With `dry_run`, nothing is
/// written and `applied` lists what would change.
pub fn import_associations(config: &Config, apps: &[AppInfo], dry_run: bool) -> ImportResult {
    let mut applied = Vec::new();
    let mut unchanged = Vec::new();
    let mut skipped = Vec::new();

    for (ext_key, value) in &config.associations {
        let ext = ext_key.trim_start_matches('.');

        let (bundle_id, display_name) = match scanner::resolve_app_or_bundle_id(apps, value) {
            Ok(pair) => pair,
            Err(reason) => {
                skipped.push((ext_key.clone(), value.clone(), reason.to_string()));
                continue;
            }
        };

        let uti_str = match uti::uti_for_extension(ext) {
            Ok(u) => u,
            Err(e) => {
                skipped.push((ext_key.clone(), display_name, e.to_string()));
                continue;
            }
        };

        // Leave associations that already match untouched.
        let current = launchservices::query_default_bundle_id(ext).ok().flatten();
        if current
            .as_deref()
            .is_some_and(|c| c.eq_ignore_ascii_case(&bundle_id))
        {
            unchanged.push((ext_key.clone(), display_name));
            continue;
        }

        let previous = current.map(|c| scanner::resolve_name(apps, &c));

        if dry_run {
            applied.push((ext_key.clone(), display_name, previous));
            continue;
        }

        match launchservices::set_default(&bundle_id, &uti_str) {
            Ok(_) => {
                applied.push((ext_key.clone(), display_name, previous));
            }
            Err(e) => {
                skipped.push((ext_key.clone(), display_name, e.to_string()));
            }
        }
    }

    ImportResult {
        applied,
        unchanged,
        skipped,
    }
}

/// Serialize a Config to TOML string with display name comments.
pub fn to_toml(config: &Config, display_names: &BTreeMap<String, String>) -> Result<String> {
    let version = env!("CARGO_PKG_VERSION");
    // Build TOML manually so we can add per-line comments with display names
    let mut lines = vec![
        format!("# Generated by openwith v{}", version),
        String::new(),
        "[associations]".to_string(),
    ];

    for (ext, bundle_id) in &config.associations {
        let escaped_key = format!("\"{}\"", ext);
        let escaped_val = format!("\"{}\"", bundle_id);
        match display_names.get(ext) {
            Some(name) => lines.push(format!("{} = {}  # {}", escaped_key, escaped_val, name)),
            None => lines.push(format!("{} = {}", escaped_key, escaped_val)),
        }
    }

    lines.push(String::new());
    Ok(lines.join("\n"))
}

/// Deserialize a Config from a TOML string.
pub fn from_toml(content: &str) -> Result<Config> {
    toml::from_str(content).context("failed to parse TOML config")
}
