use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::sync::Mutex;

use super::types::AppInfo;
use super::{launchservices, scanner, uti};

#[derive(Serialize, Deserialize)]
pub struct Config {
    pub associations: BTreeMap<String, String>,
}

pub struct ImportResult {
    pub applied: Vec<(String, String)>,
    pub skipped: Vec<(String, String, String)>,
}

/// Export current file associations to a Config.
/// Values are bundle IDs (canonical, lossless for round-tripping).
pub fn export_associations(apps: &[AppInfo]) -> Result<(Config, BTreeMap<String, String>)> {
    let mut extensions: Vec<String> = apps
        .iter()
        .flat_map(|app| app.extensions.iter().map(|e| e.to_lowercase()))
        .collect();
    extensions.sort();
    extensions.dedup();

    let associations: Mutex<BTreeMap<String, String>> = Mutex::new(BTreeMap::new());
    let display_names: Mutex<BTreeMap<String, String>> = Mutex::new(BTreeMap::new());

    std::thread::scope(|s| {
        for chunk in extensions.chunks(20) {
            let associations = &associations;
            let display_names = &display_names;
            let chunk = chunk.to_vec();
            s.spawn(move || {
                for ext in chunk {
                    if let Some(bid) = launchservices::query_default_bundle_id(&ext).ok().flatten()
                    {
                        let key = format!(".{}", ext);
                        let name = scanner::resolve_name(apps, &bid);
                        if name != bid {
                            display_names.lock().unwrap().insert(key.clone(), name);
                        }
                        associations.lock().unwrap().insert(key, bid);
                    }
                }
            });
        }
    });

    Ok((
        Config {
            associations: associations.into_inner().unwrap(),
        },
        display_names.into_inner().unwrap(),
    ))
}

/// Resolve a config value to a bundle ID. If the value looks like a bundle ID
/// (contains a dot), use it directly. Otherwise, resolve as a display name.
fn resolve_bundle_id(value: &str, apps: &[AppInfo]) -> Result<(String, String), String> {
    // Heuristic: bundle IDs contain dots (e.g. "com.apple.Preview")
    // Display names generally don't (e.g. "Preview", "Visual Studio Code")
    if value.contains('.') && !value.starts_with('.') {
        // Looks like a bundle ID — use directly, resolve name for display
        let name = scanner::resolve_name(apps, value);
        return Ok((value.to_string(), name));
    }

    // Treat as display name
    match scanner::resolve_app(apps, value) {
        Ok(app) if !app.bundle_id.is_empty() => Ok((app.bundle_id.clone(), app.name.clone())),
        Ok(app) => Err(format!("no bundle ID for '{}'", app.name)),
        Err(e) => Err(e.to_string()),
    }
}

/// Import associations from a Config, applying each one.
/// Values can be bundle IDs or display names — both are accepted.
pub fn import_associations(config: &Config, apps: &[AppInfo]) -> ImportResult {
    let mut applied = Vec::new();
    let mut skipped = Vec::new();

    for (ext_key, value) in &config.associations {
        let ext = ext_key.trim_start_matches('.');

        let (bundle_id, display_name) = match resolve_bundle_id(value, apps) {
            Ok(pair) => pair,
            Err(reason) => {
                skipped.push((ext_key.clone(), value.clone(), reason));
                continue;
            }
        };

        let uti_str = match uti::uti_for_extension(ext) {
            Ok(u) => u,
            Err(e) => {
                skipped.push((ext_key.clone(), display_name, e.to_string()));
                continue;
            }
        };

        match launchservices::set_default(&bundle_id, &uti_str) {
            Ok(_) => {
                applied.push((ext_key.clone(), display_name));
            }
            Err(e) => {
                skipped.push((ext_key.clone(), display_name, e.to_string()));
            }
        }
    }

    ImportResult { applied, skipped }
}

/// Serialize a Config to TOML string with display name comments.
pub fn to_toml(config: &Config, display_names: &BTreeMap<String, String>) -> Result<String> {
    let version = env!("CARGO_PKG_VERSION");
    // Build TOML manually so we can add per-line comments with display names
    let mut lines = vec![
        format!("# Generated by openwith v{}", version),
        String::new(),
        "[associations]".to_string(),
    ];

    for (ext, bundle_id) in &config.associations {
        let escaped_key = format!("\"{}\"", ext);
        let escaped_val = format!("\"{}\"", bundle_id);
        match display_names.get(ext) {
            Some(name) => lines.push(format!("{} = {}  # {}", escaped_key, escaped_val, name)),
            None => lines.push(format!("{} = {}", escaped_key, escaped_val)),
        }
    }

    lines.push(String::new());
    Ok(lines.join("\n"))
}

/// Deserialize a Config from a TOML string.
pub fn from_toml(content: &str) -> Result<Config> {
    toml::from_str(content).context("failed to parse TOML config")
}
